<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Day01\Day01.csproj" />
    <ProjectReference Include="..\Day02\Day02.csproj" />
    <ProjectReference Include="..\Day03\Day03.csproj" />
    <ProjectReference Include="..\Day04\Day04.csproj" />
    <ProjectReference Include="..\Day05\Day05.csproj" />
    <ProjectReference Include="..\Day06\Day06.csproj" />
  </ItemGroup>

</Project>